;;; tod-palette.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile
  (require 'clojure-elisp-runtime)
  (unless (and (boundp 'clel-runtime-version)
               (version<= "0.7.2" clel-runtime-version))
    (error "clojure-elisp-runtime %s is too old for this file (needs %s)"
           (if (boundp 'clel-runtime-version) clel-runtime-version "(pre-0.7.2)")
           "0.7.2")))
(require 'tod-color)
(require 'tod-process)
(require 'json)

;;; Code:



(defvar tod-palette-semantic-hues (list (list :red 0.0) (list :orange 30.0) (list :yellow 55.0) (list :green 120.0) (list :cyan 185.0) (list :blue 220.0) (list :magenta 295.0)) "Semantic colour names and their target hues in degrees.")

(defvar tod-palette-warm-light "#ff9e3d" "Colour mixed into backgrounds while the sun is low.")

(defun tod-palette-read-wal (file)
  "Return pywal's palette in FILE as an alist, or nil when unreadable.\nThe alist has :background, :foreground, :cursor, :wallpaper and :colors,\nthe sixteen colours color0 to color15 in order."
  (when (and file (file-readable-p file))
    (condition-case nil
    (let* ((data (with-temp-buffer
    (insert-file-contents file)
    (json-parse-buffer :object-type 'alist :array-type 'list)))
        (special (alist-get 'special data))
        (colors (alist-get 'colors data)))
    (list (cons :background (alist-get 'background special)) (cons :foreground (alist-get 'foreground special)) (cons :cursor (alist-get 'cursor special)) (cons :wallpaper (alist-get 'wallpaper data)) (cons :colors (mapcar (lambda (i)
    (alist-get (intern (format "color%d" i)) colors)) (number-sequence 0 15)))))
  (error nil))))

(defun tod-palette-accent-candidates (wal)
  "Return the saturated accent colours of the pywal palette WAL.\nSlots 0, 7, 8 and 15 hold the background, foreground and greys."
  (let* ((colors (clel-get wal :colors)))
    (seq-filter (lambda (c)
    (and (tod-color-hex-to-rgb c) (>= (tod-color-saturation c) 0.15))) (mapcar (lambda (i)
    (clel-nth colors i)) (list 1 2 3 4 5 6 9 10 11 12 13 14)))))

(defun tod-palette-nearest-accent (candidates hue)
  "Return the colour of CANDIDATES nearest in hue to HUE, or nil.\nColours more than 40 degrees away do not count."
  (let* ((scored (mapcar (lambda (c)
    (cons (tod-color-hue-distance (tod-color-hue-degrees c) hue) c)) candidates))
        (best (car (clel-sort (lambda (a b)
    (< (car a) (car b))) scored))))
    (when (and best (<= (car best) 40.0))
    (cdr best))))

(defun tod-palette-tint (wal phase warmth)
  "Return WAL with its background warmed towards low sunlight.\nPHASE is the phase of the day; golden-hour and civil-twilight get\nWARMTH of the warm light mixed in, other phases none."
  (if (and (memq phase (list 'golden-hour 'civil-twilight)) (> warmth 0.0)) (cons (cons :background (tod-color-mix (clel-get wal :background) tod-palette-warm-light warmth)) wal) wal))

(defun tod-palette-semantic (wal ratio)
  "Return a semantic palette from the pywal palette WAL.\nEvery accent reaches RATIO against the background and the foreground\nreaches at least 7.  Keys are :bg, :fg, :cursor, :comment and the names\nin `tod-palette-semantic-hues'."
  (let* ((bg (or (clel-get wal :background) "#000000"))
        (fg (tod-color-ensure-contrast (or (clel-get wal :foreground) (if (tod-color-dark-p bg) "#ffffff" "#000000")) bg (max ratio 7.0)))
        (candidates (tod-palette-accent-candidates wal))
        (accents (mapcar (lambda (entry)
    (let* ((hue (clel-second entry))
        (base (or (tod-palette-nearest-accent candidates hue) (tod-color-from-hsl (/ hue 360.0) 0.55 0.5))))
    (cons (clel-first entry) (tod-color-ensure-contrast base bg ratio)))) tod-palette-semantic-hues))
        (grey (or (clel-nth (clel-get wal :colors) 8) (tod-color-mix fg bg 0.45))))
    (append (list (cons :bg bg) (cons :fg fg) (cons :cursor (tod-color-ensure-contrast (or (clel-get wal :cursor) fg) bg 3.0)) (cons :comment (tod-color-ensure-contrast grey bg ratio))) accents)))

(defun tod-palette-wal-colors-file (cache-dir system)
  "Return where pywal writes colors.json for CACHE-DIR.\nWhen SYSTEM is non-nil pywal uses its global cache, which also recolours\nterminals and other programs; otherwise it writes under CACHE-DIR."
  (if system (expand-file-name "wal/colors.json" (or (getenv "XDG_CACHE_HOME") (expand-file-name "~/.cache"))) (expand-file-name "wal/colors.json" cache-dir)))

(defun tod-palette-wal-commands (image cache-dir light system)
  "Return the commands that make pywal derive a palette from IMAGE.\nLIGHT asks for a light scheme.  When SYSTEM is nil pywal is kept to\nCACHE-DIR and told not to touch terminals, the wallpaper or other\nprograms; when non-nil it recolours the desktop as pywal usually does."
  (let* ((flags (append (list "-i" (expand-file-name image) "-n" "-q") (when light
    (list "-l")))))
    (if system (list (append (list "wal") flags)) (list (append (list "env" (clel-str "PYWAL_CACHE_DIR=" (expand-file-name "wal" cache-dir)) "NO_FUN=1" "wal") flags (list "-s" "-t" "-e"))))))

(defun tod-palette-generate (image cache-dir light system done)
  "Derive a pywal palette from IMAGE, then call DONE with it.\nDONE receives the palette from `tod-palette-read-wal' and an error\nmessage, one of them nil.  CACHE-DIR, LIGHT and SYSTEM are as for\n`tod-palette-wal-commands'."
  (let* ((out (tod-palette-wal-colors-file cache-dir system)))
    (tod-process-run 'palette (tod-palette-wal-commands image cache-dir light system) (lambda (ok message)
    (let* ((wal (when ok
    (tod-palette-read-wal out))))
    (funcall done wal (cond
  ((not ok) message)
  ((null wal) (clel-str "pywal wrote no palette to " out))
  (t nil))))))))

(provide 'tod-palette)
;;; tod-palette.el ends here
