;;; tod.el --- Themes and wallpapers that follow the sun and the seasons  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Pedro G. Branquinho

;; Author: Pedro G. Branquinho <pedrogbranquinho@gmail.com>
;; URL: https://github.com/BuddhiLW/tod
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1") (clel "0.8.0"))
;; Keywords: faces, calendar, convenience
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is not part of GNU Emacs.
;; Generated by ClojureElisp: edit the .cljel source, not this file.

;;; Commentary:

;; tod works out where the sun stands for your location: night, the three
;; twilights, golden hour or day, whether it is rising or setting, the
;; astronomical season (flipped south of the equator), the month and the
;; calendar periods in effect.  Ordered rules in `tod-looks' turn that into
;; a look: an Emacs theme, a desktop wallpaper, and optionally a palette
;; that pywal derives from the wallpaper and tod repairs to readable
;; contrast.  `tod-mode' keeps the look current, waking at each twilight
;; boundary rather than polling.
;;
;; Set `tod-latitude' and `tod-longitude' (or `calendar-latitude' and
;; `calendar-longitude'), then enable `tod-mode'.  M-x tod-describe shows the
;; sun, the season, today's boundaries and the look tod picked.  Put
;; %%(tod-diary-sun) in a diary or Org file to see the day's twilight
;; times in the agenda.
;;
;; Wallpapers come from `tod-wallpaper-directory', organised as
;; SEASON/PHASE/, with any for either part and _period/NAME/ or _month/MM/
;; for calendar overrides.  Setters for GNOME, Cinnamon, MATE, KDE Plasma,
;; Xfce, Hyprland, sway, swww, swaybg, feh, xwallpaper and nitrogen are
;; built in, and lazywal plays video wallpapers; register more with
;; `tod-wallpaper-register-setter'.

;;; Code:

(eval-and-compile
  (require 'clel)
  (unless (and (boundp 'clel-runtime-version)
               (version<= "0.8.0" clel-runtime-version))
    (error "Installed clel runtime %s is too old for this file (needs %s)"
           (if (boundp 'clel-runtime-version) clel-runtime-version "(pre-0.8.0)")
           "0.8.0")))
(require 'tod-moment)
(require 'tod-look)
(require 'tod-sun)
(require 'tod-theme)
(require 'tod-wallpaper)
(require 'tod-palette)
(require 'xdg)



(defgroup tod nil
  "Themes and wallpapers that follow the sun and the seasons."
  :group 'faces
  :prefix "tod-")

(defcustom tod-latitude nil
  "Latitude in degrees, north positive, or nil to use `calendar-latitude'."
  :type '(choice (const :tag "Use calendar-latitude" nil) number)
  :group 'tod)

(defcustom tod-longitude nil
  "Longitude in degrees, east positive, or nil to use `calendar-longitude'."
  :type '(choice (const :tag "Use calendar-longitude" nil) number)
  :group 'tod)

(defcustom tod-phases tod-moment-default-ladder
  "Phases of the day by the sun's minimum altitude in degrees.
Each entry is (PHASE MIN-ALTITUDE), highest first; the last entry
catches everything below the one before it."
  :type '(repeat (list symbol number))
  :group 'tod)

(defcustom tod-looks '((:phase night :season winter :theme (ef-winter ef-night modus-vivendi-tinted modus-vivendi)) (:phase night :season autumn :theme (ef-autumn ef-night modus-vivendi)) (:phase night :theme (ef-night ef-dark modus-vivendi)) (:phase (astronomical-twilight nautical-twilight) :theme (ef-dream ef-maris-dark modus-vivendi-tinted modus-vivendi)) (:phase civil-twilight :rising t :theme (ef-elea-dark modus-vivendi-tinted modus-vivendi)) (:phase civil-twilight :theme (ef-melissa-dark ef-autumn modus-vivendi-tinted modus-vivendi)) (:phase golden-hour :theme (ef-melissa-light modus-operandi-tinted modus-operandi)) (:season spring :theme (ef-spring modus-operandi-tinted modus-operandi)) (:season summer :theme (ef-summer ef-day modus-operandi)) (:season autumn :theme (ef-cyprus ef-day modus-operandi-tinted modus-operandi)) (:season winter :theme (ef-frost modus-operandi)) (:theme modus-operandi :wallpaper t))
  "Rules that turn the sun and the calendar into a look.
Each rule is a plist of criteria and attributes.  Criteria are the keys
of `tod-look-criteria': :phase, :season, :month, :rising, :period,
:hour, :altitude and :when.  Attributes are:

  :theme      a theme, or a list of alternatives tried in order
  :wallpaper  a file, a directory to pick from, or t for the layout
              under `tod-wallpaper-directory'
  :palette    wal to build the theme from the wallpaper with pywal

Each attribute comes from the first matching rule that sets it."
  :type '(repeat (plist :key-type symbol :value-type sexp))
  :group 'tod)

(defcustom tod-holidays nil
  "Holidays that count as periods, in the format of `calendar-holidays'.
Nil means use `calendar-holidays' itself."
  :type '(choice (const :tag "Use calendar-holidays" nil) (repeat sexp))
  :group 'tod)

(defcustom tod-periods nil
  "Named date spans that count as periods.
Each entry is (NAME (MONTH DAY) (MONTH DAY)), inclusive; a span whose
end comes before its start wraps over the new year."
  :type '(repeat (list string (list integer integer) (list integer integer)))
  :group 'tod)

(defcustom tod-wallpaper-directory nil
  "Root of the wallpaper layout, or nil for tod/ in the Pictures folder."
  :type '(choice (const :tag "Pictures/tod" nil) directory)
  :group 'tod)

(defcustom tod-palette-scope 'isolated
  "How far a pywal palette reaches.
isolated keeps pywal's output in tod's cache and leaves terminals and
other programs alone; system lets pywal recolour the desktop as it does
when run by hand or by lazywal."
  :type '(choice (const isolated) (const system))
  :group 'tod)

(defcustom tod-minimum-contrast 4.5
  "WCAG contrast every colour of a generated palette must reach."
  :type 'number
  :group 'tod)

(defcustom tod-warmth 0.06
  "How much warm light tints generated backgrounds while the sun is low."
  :type 'number
  :group 'tod)

(defcustom tod-refresh-interval 1800
  "Longest time in seconds between two checks of the look."
  :type 'integer
  :group 'tod)

(defcustom tod-apply-functions nil
  "Functions called after tod applies a look, with the look and moment."
  :type 'hook
  :group 'tod)

(defcustom tod-phase-change-functions nil
  "Functions called when the phase changes, with new phase, old phase and moment."
  :type 'hook
  :group 'tod)

(defvar tod-mode)

(declare-function dbus-register-signal "dbus")

(declare-function dbus-unregister-object "dbus")

(declare-function package-install "package")

(defvar tod--timer nil
  "Timer that wakes tod at the next boundary.")

(defvar tod--moment nil
  "The moment tod last resolved.")

(defvar tod--look nil
  "The look tod last applied.")

(defvar tod--wallpaper nil
  "The wallpaper file tod last applied.")

(defvar tod--palette-image nil
  "The image the current generated palette was derived from.")

(defvar tod--override-until nil
  "Time until which a theme the user enabled by hand is respected.")

(defvar tod--resume-signal nil
  "D-Bus registration for resume from suspend, when there is one.")

(defvar tod--last-error nil
  "The last error tod met while applying a look, or nil.")

(defun tod-location ()
  "Return (LATITUDE LONGITUDE) from tod's or the calendar's settings, or nil."
  (let* ((lat (or tod-latitude (and (boundp 'calendar-latitude) calendar-latitude (calendar-latitude))))
        (lon (or tod-longitude (and (boundp 'calendar-longitude) calendar-longitude (calendar-longitude)))))
    (when (and (numberp lat) (numberp lon))
    (list (float lat) (float lon)))))

(defun tod-layout-root ()
  "Return the wallpaper layout root directory."
  (or tod-wallpaper-directory (expand-file-name "tod" (or (xdg-user-dir "PICTURES") (expand-file-name "~/Pictures")))))

(defun tod-cache-directory ()
  "Return the directory tod keeps extracted frames and palettes in."
  (expand-file-name "tod" (or (getenv "XDG_CACHE_HOME") (expand-file-name "~/.cache"))))

(defun tod-holiday-list ()
  "Return the holiday list periods are drawn from."
  (or tod-holidays (and (boundp 'calendar-holidays) calendar-holidays)))

(defun tod-current-moment (time)
  "Return the moment at TIME for the configured location, or nil."
  (let* ((loc (tod-location)))
    (when loc
    (tod-moment-at (or time (current-time)) (clel-nth loc 0) (clel-nth loc 1) tod-phases (tod-holiday-list) tod-periods))))

(defun tod-pick-look (m)
  "Return the look `tod-looks' gives the moment M."
  (tod-look-resolve tod-looks m tod-look-criteria #'tod-theme-available-p))

(defun tod--note-error (msg)
  "Remember MSG as tod's last error and show it."
  (setq tod--last-error msg)
  (message "Tod: %s" msg))

(defun tod--light-phase-p (phase)
  "Return non-nil when PHASE is bright enough for a light palette."
  (memq phase (list 'day 'golden-hour)))

(defun tod--apply-palette (image m)
  "Build and enable a theme from the palette pywal derives from IMAGE.
M is the moment, whose phase decides light or dark and warmth."
  (setq tod--palette-image image)
  (tod-palette-generate image (tod-cache-directory) (tod--light-phase-p (clel-get m :phase)) (eq tod-palette-scope 'system) (lambda (wal err)
    (if wal (let* ((p (tod-palette-semantic (tod-palette-tint wal (clel-get m :phase) tod-warmth) tod-minimum-contrast)))
    (tod-theme-define-palette-theme 'tod-wal p)
    (tod-theme-switch 'tod-wal)) (tod--note-error err)))))

(defun tod--theme-overridden-p ()
  "Return non-nil while a theme the user chose by hand is respected."
  (and tod--override-until (time-less-p nil tod--override-until)))

(defun tod-apply-look (look m)
  "Apply LOOK for the moment M: theme, wallpaper and palette.
Parts that did not change are left alone, so applying the same look
twice does nothing."
  (let* ((wants-palette (eq (clel-get look :palette) 'wal))
        (theme-name (clel-get look :theme))
        (file (when (clel-get look :wallpaper)
    (tod-wallpaper-choose-file (clel-get look :wallpaper) m (tod-layout-root)))))
    (when (and theme-name (not wants-palette) (not (tod--theme-overridden-p)))
    (tod-theme-switch theme-name))
    (cond
  ((and file (not (equal file tod--wallpaper))) (let* ((p (tod-wallpaper-apply-file file tod-wallpaper-setters (tod-cache-directory) (lambda (ok message)
    (if ok nil (progn
  (tod--note-error message)))))))
    (setq tod--wallpaper file)
    (when (and wants-palette (clel-get p :image) (not (tod--theme-overridden-p)))
    (run-at-time 2.0 nil (lambda ()
    (tod--apply-palette (clel-get p :image) m))))))
  ((and wants-palette (not (tod--theme-overridden-p)) (or (not (eq (clel-get tod--moment :phase) (clel-get m :phase))) (null tod--palette-image))) (let* ((image (or (and tod--wallpaper (clel-get (tod-wallpaper-plan tod--wallpaper tod-wallpaper-setters (tod-cache-directory)) :image)) (clel-get (tod-palette-read-wal (tod-palette-wal-colors-file (tod-cache-directory) t)) :wallpaper))))
    (if (and image (file-readable-p image)) (tod--apply-palette image m) (tod--note-error "No wallpaper image to derive a palette from"))))
  (t nil))
    (run-hook-with-args 'tod-apply-functions look m)
    look))

(defun tod-next-wakeup (time)
  "Return the Lisp time tod should look again after TIME.
It is the next phase boundary, the next local midnight or
`tod-refresh-interval' from now, whichever comes first."
  (let* ((loc (tod-location))
        (boundary (when loc
    (tod-moment-next-change time (clel-nth loc 0) (clel-nth loc 1) tod-phases)))
        (candidates (delq nil (list boundary (tod-moment-next-midnight time) (time-add time tod-refresh-interval)))))
    (car (clel-sort (lambda (a b)
    (time-less-p a b)) candidates))))

(defun tod--arm-timer ()
  "Arrange for `tod-refresh' to run just after the next boundary."
  (when (timerp tod--timer)
    (cancel-timer tod--timer))
  (let* ((delay (max 1.0 (+ 1.0 (float-time (time-subtract (tod-next-wakeup nil) nil))))))
    (setq tod--timer (run-at-time delay nil #'tod-refresh))))

(defun tod-refresh ()
  "Resolve the look for now, apply what changed and schedule the next check."
  (interactive)
  (let* ((m (tod-current-moment nil)))
    (if (null m) (tod--note-error "Set `tod-latitude' and `tod-longitude' first") (let* ((look (tod-pick-look m))
        (old-phase (clel-get tod--moment :phase)))
    (setq tod--last-error nil)
    (condition-case err
    (tod-apply-look look m)
  (error (tod--note-error (error-message-string err))))
    (when (and tod--override-until (not (tod--theme-overridden-p)))
    (setq tod--override-until nil))
    (unless (eq old-phase (clel-get m :phase))
    (run-hook-with-args 'tod-phase-change-functions (clel-get m :phase) old-phase m))
    (setq tod--moment m)
    (setq tod--look look))))
  (when tod-mode
    (tod--arm-timer)))

(defun tod--on-enable-theme (theme)
  "Respect THEME until the next boundary when the user enabled it by hand."
  (when (and (not tod-theme--applying) (not (eq theme 'user)) (tod-theme-color-scheme-p theme) (not (eq theme (clel-get tod--look :theme))))
    (setq tod--override-until (tod-next-wakeup nil))))

(defun tod--on-resume (sleeping)
  "Refresh after the machine wakes up; SLEEPING is non-nil on the way down."
  (unless sleeping
    (run-at-time 3.0 nil #'tod-refresh)))

(defun tod--watch-resume ()
  "Register for logind's resume signal when D-Bus is available."
  (when (and (featurep 'dbusbind) (require 'dbus nil t))
    (setq tod--resume-signal (condition-case nil
    (dbus-register-signal :system "org.freedesktop.login1" "/org/freedesktop/login1" "org.freedesktop.login1.Manager" "PrepareForSleep" #'tod--on-resume)
  (error nil)))))

(defun tod--start ()
  "Start following the sun."
  (when (null (tod-location))
    (setq tod-mode nil)
    (user-error "Set `tod-latitude' and `tod-longitude' before enabling tod-mode"))
  (add-hook 'enable-theme-functions #'tod--on-enable-theme)
  (tod--watch-resume)
  (tod-refresh))

(defun tod--stop ()
  "Stop following the sun, leaving the current look in place."
  (when (timerp tod--timer)
    (cancel-timer tod--timer))
  (setq tod--timer nil)
  (remove-hook 'enable-theme-functions #'tod--on-enable-theme)
  (when tod--resume-signal
    (condition-case nil
    (dbus-unregister-object tod--resume-signal)
  (error nil))
    (setq tod--resume-signal nil)))

;;;###autoload
(define-minor-mode tod-mode
  "Keep themes and wallpaper in step with the sun and the seasons.
When enabled, tod applies the look `tod-looks' gives the current moment
and wakes at every twilight boundary, local midnight and at most every
`tod-refresh-interval' seconds to apply the next one."
  :global t
  :lighter " tod"
  :group 'tod
  (if tod-mode (tod--start) (tod--stop)))

(defun tod--phase-label (phase)
  "Return a readable name for the symbol PHASE."
  (let* ((words (string-replace "-" " " (symbol-name phase))))
    (clel-str (upcase (substring words 0 1)) (substring words 1))))

(defun tod--phase-entered (height rising)
  "Return the phase the sun enters when crossing HEIGHT, RISING or not."
  (let* ((steps tod-phases)
        (above (seq-find (lambda (s)
    (clel-equal (clel-second s) height)) steps))
        (below (clel-second (seq-drop-while (lambda (s)
    (not (clel-equal (clel-second s) height))) steps))))
    (clel-first (if rising above below))))

(defun tod-event-label (height rising)
  "Return the diary label of the crossing of HEIGHT, RISING or not."
  (cond
  ((and (clel-equal height -0.833) rising) "Sunrise")
  ((clel-equal height -0.833) "Sunset")
  (t (clel-str (tod--phase-label (or (tod--phase-entered height rising) 'night)) " begins"))))

(defun tod--format-events (day lat lon)
  "Return the crossings of DAY as \"HH:MM Label\" strings.
LAT and LON give the place."
  (let* ((start (encode-time (list 0 0 0 (clel-nth day 1) (clel-nth day 0) (clel-nth day 2) nil -1 nil)))
        (end (time-add start 86400))
        (events (seq-filter (lambda (e)
    (and (not (time-less-p (clel-get e :time) start)) (time-less-p (clel-get e :time) end))) (tod-sun-events-around (time-add start 43200) lat lon (tod-moment-ladder-heights tod-phases)))))
    (mapcar (lambda (e)
    (clel-str (format-time-string "%H:%M" (clel-get e :time)) " " (tod-event-label (clel-get e :height) (clel-get e :rising)))) events)))

;;;###autoload
(defun tod-diary-sun ()
  "Return the day's twilight and sun events for diary and Org agenda.
Use it as %%(tod-diary-sun) in a diary or Org file: each event becomes
its own timed agenda line."
  (let* ((diary-var (intern-soft "date"))
        (day (when (and diary-var (boundp diary-var))
    (symbol-value diary-var)))
        (loc (tod-location)))
    (when (and day loc)
    (string-join (tod--format-events day (clel-nth loc 0) (clel-nth loc 1)) "; "))))

;;;###autoload
(defun tod-describe ()
  "Show the sun, the season, today's boundaries and the chosen look."
  (interactive)
  (let* ((m (tod-current-moment nil)))
    (when (null m)
    (user-error "Set `tod-latitude' and `tod-longitude' first"))
    (let* ((look (tod-pick-look m))
        (loc (tod-location))
        (wake (tod-next-wakeup nil)))
    (with-help-window "*tod*" (princ (format "Location   %.4f, %.4f\n" (clel-nth loc 0) (clel-nth loc 1))) (princ (format "Sun        %.1f° altitude, %.0f° bearing, %s\n" (clel-get m :altitude) (clel-get m :azimuth) (if (clel-get m :rising) "rising" "setting"))) (princ (format "Phase      %s\n" (tod--phase-label (clel-get m :phase)))) (princ (format "Season     %s (%d%% through)\n" (tod--phase-label (clel-get m :season)) (round (* 100 (clel-get m :season-progress))))) (princ (format "Periods    %s\n" (or (string-join (clel-get m :periods) ", ") ""))) (princ (format "Next check %s\n\n" (format-time-string "%F %H:%M" wake))) (princ "Today\n") (dolist (line (clel-seq (tod--format-events (tod-moment-local-date nil) (clel-nth loc 0) (clel-nth loc 1))))
    (princ (clel-str "  " line "\n"))) (princ "\nLook\n") (princ (format "  theme      %s\n" (or (clel-get look :theme) "unchanged"))) (princ (format "  wallpaper  %s\n" (or (when (clel-get look :wallpaper)
    (tod-wallpaper-choose-file (clel-get look :wallpaper) m (tod-layout-root))) "none"))) (princ (format "  palette    %s\n" (or (clel-get look :palette) "theme's own"))) (princ (format "\nWallpaper setters (%s session, %s)\n" (or (tod-wallpaper-session-type) "unknown") (string-join (tod-wallpaper-desktop-names) ":"))) (dolist (s (clel-seq (tod-wallpaper-candidates tod-wallpaper-setters 'image (tod-wallpaper-session-type) (tod-wallpaper-desktop-names))))
    (let* ((why (tod-wallpaper-missing s)))
    (princ (format "  %-12s %s\n" (clel-get s :id) (if why (string-join why ", ") "ready"))))) (when tod--last-error
    (princ (format "\nLast error: %s\n" tod--last-error)))))))

;;;###autoload
(defun tod-preview (phase season)
  "Apply the look for PHASE and SEASON now, without touching the wallpaper.
The next boundary restores the real look."
  (interactive (list (intern (completing-read "Phase: " (mapcar (lambda (s)
    (symbol-name (clel-first s))) tod-phases) nil t)) (intern (completing-read "Season: " (list "spring" "summer" "autumn" "winter") nil t))))
  (let* ((m (or (tod-current-moment nil) (clel-array-map :periods nil)))
        (fake (cons (cons :phase phase) (cons (cons :season season) m)))
        (look (tod-pick-look fake)))
    (when (clel-get look :theme)
    (tod-theme-switch (clel-get look :theme)))
    (message "Previewing %s in %s: %s" phase season (or (clel-get look :theme) "no theme"))))

;;;###autoload
(defun tod-install-themes ()
  "Install the ef-themes collection, which the default looks prefer."
  (interactive)
  (when (y-or-n-p "Install ef-themes from GNU ELPA? ")
    (package-install 'ef-themes)))

(provide 'tod)
;;; tod.el ends here
